### PR TITLE
Add rare event chart capability

### PR DESCRIPTION
**Pull request by francisbarton**
If the rare event chart flag is set to "Y" in the report_config and there is calculated "days between" data in the "none" sheet of the measure data file, a "days between" chart should be created.

All tests and package checks pass.

Designed to partially address issue #4

### CODE REVIEW

**Comment by ThomUK** [comment]
This is great, thanks Fran!
Particular nod to the effort to untangle conflicts following recent dev work.

I'd like to give it a test - drive before merging to understand how to use the functionality.
In doing that I'll also understand enough to write a vignette covering theory and usage.

**Comment by ThomUK** [comment]
One question, what is partial about the change?
> Designed to partially address issue #4

**Comment by francisbarton** [comment]
I think it's partial in two ways:

* Looking at issue #4 there is a suggestion that it needs to handle two types of chart. My work so far has only been thinking about "days between events", and I was conscious that I hadn't planned around any other type of data. However, that might be an issue around creating the data in the first place, rather than how this package handles the chart creation.
* I haven't created any tests for this really, so yes it does need test-driving! I am getting a strange problem in some charts, but not others, where the data will be between Jan 2020 and Oct 2023 but the x axis labels can start at November 2019 and run on to January 2024. I wanted to get the work pushed here soon however, as I was aware that your work going into main meant that the branches were becoming increasingly divergent.

**Comment by ThomUK** [comment]
I really appreciate this contribution Fran.  I'm going to pause other development until we find a way to get this merged.

Quick review:
- [ ] Ideally need to mark to final point on a rare-event chart to reflect that it is a provisional point (ie. this is what the chart would look like if we had an event today).  For simplicity, the other option is to not draw the final point.  Users may get used to this in time, and with explanation.
- [ ] Potential for confusion with two different-looking charts with the same measure ref and title.  The Y axis is different, but we could consider eg. appending "(time between)" to the measure title for clarity.  This would make the rolled up view in particular clearer.  
image
- [ ] Tests (light touch - what do we need to prevent accidental regression later)
- [ ] Does the "none" sheet work when there are multiple rare-event measures, with different event dates in columns?  We probably need to demo that for users by adding a 2nd rare event measure to this sheet to show how it might look.
image

- [ ] Docs need updating to read in the "none" worksheet of data.xlsx as part of constructing the `measure_data` object.
- [ ] Vignette covering the how and why of rare-event charts, and referring to the [Health Care Data Guide](https://www.oreilly.com/library/view/the-health-care/9781118085882/) for further reading.
- [ ] Add commentary to the measure 99 charts explaining what they are in the example report.  We could take this further and have similar commentary for each successive chart, each introducing a new concept (1 = basic plot, 2 = target line, 3 = improvement direction = increase, 4 = improvement_direction = decrease, 5 = rebase, 6 = rare events on an XmR chart, 7 = rare events on a T chart, etc).


I love:
* Room 101
* 99 problems

Possible changes after initial merge:
- [ ] More thought on generalising the naming and the API, to support later changes.  Is aggregation = "none" the right concept?  Would aggregation = "T-chart" or "time-between" be a valid concept?  We might in future have an aggregation = "G-chart", or "events-between".  I'm not sure of the right answer.
- [ ] Computing targets on the rare-event chart.  A target of 0 events per month would be Inf days between, but target of 1 event/mth = 30.4 days between.  A moot point if most rare events are target 0, but technically feasible.
- [ ] Potential to generalise further and accept raw event data (id, and dttm), and convert this internally within the package.  This could work for weekly and monthly aggregations, as well as for rare events, as an alternative data read-in format.

**Comment by ThomUK** [comment]
I'm merging this to a temporary dev branch, because I want to change the API slightly.  
I'd like rare events to be supplied as an event list, and for the processing to be done inside this package.  This is in keeping with the method used by the making data count excel tools.  

I will open issues for the rare events vignette, and the improvement to the commentary for each chart in the example report.

**Pull request merged**
